#!/usr/bin/env php
<?php

if (file_exists(__DIR__.'/../../autoload.php')) {
    require __DIR__.'/../../autoload.php';
} else {
    require __DIR__.'/vendor/autoload.php';
}

$app = new Symfony\Component\Console\Application('Arch Installer', '0.0.2');
$app->add(new UnikCodes\Console\Commands\MakeNewCommand);
$app->add(new UnikCodes\Console\Commands\MakeInstallCommand);
$app->run();